version: 2

sources:
  - name: erp
    database: adventureworks-dw-394319  
    schema: sap_adw
    description: Fonte de dados das vendas do SAP Adventure Works
    tables:
      - name: customer
        columns:
          - name: customerid
            tests:
             - unique
             - not_null
      - name: person
        columns:
          - name: businessentityid
            tests:
             - unique
             - not_null
      - name: personcreditcard 
        columns:
          - name: businessentityid
            tests:
             - unique
             - not_null             
      - name: creditcard
        columns:
          - name: creditcardid
            tests:
             - unique
             - not_null
      - name: address
        columns:
          - name: addressid
            tests:
             - unique
             - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            tests:
             - unique
             - not_null  
      - name: salesterritory 
        columns:
          - name: territoryid
            tests:
             - unique
             - not_null 
      
         
    